const {
  DB_URL,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD,
} = process.env;

if (
  !DB_URL ||
  !GITHUB_CLIENT_ID ||
  !GITHUB_CLIENT_SECRET ||
  !SPOTIFY_CLIENT_ID ||
  !SPOTIFY_CLIENT_SECRET ||
  !CLOUDINARY_API_KEY ||
  !CLOUDINARY_API_SECRET ||
  !CLOUDINARY_CLOUD
) {
  throw new Error("missing env var");
}

export const env = {
  DB_URL,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD,
};
