/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationOrganizationViewRouteImport } from './routes/organization.$organizationView'
import { Route as AuthAuthViewRouteImport } from './routes/auth.$authView'
import { Route as ArtistsIdRouteImport } from './routes/artists_.$id'
import { Route as AlbumsIdRouteImport } from './routes/albums_.$id'
import { Route as AdminTrackInfoRouteImport } from './routes/admin.trackInfo'
import { Route as AdminSystemSettingsRouteImport } from './routes/admin.systemSettings'
import { Route as AccountAccountViewRouteImport } from './routes/account.$accountView'
import { ServerRoute as ApiSplatServerRouteImport } from './routes/api.$'
import { ServerRoute as ApiMediaIdServerRouteImport } from './routes/api_.media.$id'
import { ServerRoute as ApiRpcSplatServerRouteImport } from './routes/api.rpc.$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api.auth.$'

const rootServerRouteImport = createServerRootRoute()

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrganizationViewRoute =
  OrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIdRoute = ArtistsIdRouteImport.update({
  id: '/artists_/$id',
  path: '/artists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIdRoute = AlbumsIdRouteImport.update({
  id: '/albums_/$id',
  path: '/albums/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrackInfoRoute = AdminTrackInfoRouteImport.update({
  id: '/admin/trackInfo',
  path: '/admin/trackInfo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemSettingsRoute = AdminSystemSettingsRouteImport.update({
  id: '/admin/systemSettings',
  path: '/admin/systemSettings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatServerRoute = ApiSplatServerRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMediaIdServerRoute = ApiMediaIdServerRouteImport.update({
  id: '/api_/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiRpcSplatServerRoute = ApiRpcSplatServerRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/admin/systemSettings': typeof AdminSystemSettingsRoute
  '/admin/trackInfo': typeof AdminTrackInfoRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/admin/systemSettings': typeof AdminSystemSettingsRoute
  '/admin/trackInfo': typeof AdminTrackInfoRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/admin/systemSettings': typeof AdminSystemSettingsRoute
  '/admin/trackInfo': typeof AdminTrackInfoRoute
  '/albums_/$id': typeof AlbumsIdRoute
  '/artists_/$id': typeof ArtistsIdRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/artists'
    | '/search'
    | '/settings'
    | '/account/$accountView'
    | '/admin/systemSettings'
    | '/admin/trackInfo'
    | '/albums/$id'
    | '/artists/$id'
    | '/auth/$authView'
    | '/organization/$organizationView'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/artists'
    | '/search'
    | '/settings'
    | '/account/$accountView'
    | '/admin/systemSettings'
    | '/admin/trackInfo'
    | '/albums/$id'
    | '/artists/$id'
    | '/auth/$authView'
    | '/organization/$organizationView'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/artists'
    | '/search'
    | '/settings'
    | '/account/$accountView'
    | '/admin/systemSettings'
    | '/admin/trackInfo'
    | '/albums_/$id'
    | '/artists_/$id'
    | '/auth/$authView'
    | '/organization/$organizationView'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRoute
  ArtistsRoute: typeof ArtistsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  AdminSystemSettingsRoute: typeof AdminSystemSettingsRoute
  AdminTrackInfoRoute: typeof AdminTrackInfoRoute
  AlbumsIdRoute: typeof AlbumsIdRoute
  ArtistsIdRoute: typeof ArtistsIdRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  OrganizationOrganizationViewRoute: typeof OrganizationOrganizationViewRoute
}
export interface FileServerRoutesByFullPath {
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
  '/api/media/$id': typeof ApiMediaIdServerRoute
}
export interface FileServerRoutesByTo {
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
  '/api/media/$id': typeof ApiMediaIdServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
  '/api_/media/$id': typeof ApiMediaIdServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/$' | '/api/auth/$' | '/api/rpc/$' | '/api/media/$id'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/$' | '/api/auth/$' | '/api/rpc/$' | '/api/media/$id'
  id: '__root__' | '/api/$' | '/api/auth/$' | '/api/rpc/$' | '/api_/media/$id'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSplatServerRoute: typeof ApiSplatServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiRpcSplatServerRoute: typeof ApiRpcSplatServerRoute
  ApiMediaIdServerRoute: typeof ApiMediaIdServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$organizationView': {
      id: '/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/organization/$organizationView'
      preLoaderRoute: typeof OrganizationOrganizationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists_/$id': {
      id: '/artists_/$id'
      path: '/artists/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof ArtistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums_/$id': {
      id: '/albums_/$id'
      path: '/albums/$id'
      fullPath: '/albums/$id'
      preLoaderRoute: typeof AlbumsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trackInfo': {
      id: '/admin/trackInfo'
      path: '/admin/trackInfo'
      fullPath: '/admin/trackInfo'
      preLoaderRoute: typeof AdminTrackInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/systemSettings': {
      id: '/admin/systemSettings'
      path: '/admin/systemSettings'
      fullPath: '/admin/systemSettings'
      preLoaderRoute: typeof AdminSystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api_/media/$id': {
      id: '/api_/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRoute,
  ArtistsRoute: ArtistsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AccountAccountViewRoute: AccountAccountViewRoute,
  AdminSystemSettingsRoute: AdminSystemSettingsRoute,
  AdminTrackInfoRoute: AdminTrackInfoRoute,
  AlbumsIdRoute: AlbumsIdRoute,
  ArtistsIdRoute: ArtistsIdRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  OrganizationOrganizationViewRoute: OrganizationOrganizationViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSplatServerRoute: ApiSplatServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiRpcSplatServerRoute: ApiRpcSplatServerRoute,
  ApiMediaIdServerRoute: ApiMediaIdServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
